Be-Secure/BeSLab

beslab/0.0.1/besman-beslab-env.sh, beslab/0.0.1/besman-beslighthouse.sh, beslab/0.0.1/besman-gitlab.sh, beslab_genesis.yaml
Added BesLighthouse installation script and updated Genesis file.
=> Added BesLighthouse and updated Genesis file

BeSLab_Personal.ipynb, BeSLab_Private.ipynb, BeSLab_Public.ipynb, beslab/0.0.1/besman-beslab-env.sh, beslab/0.0.1/besman-beslighthouse.sh, beslab/0.0.1/besman-gitlab.sh, beslab_genesis.yaml
Some typo fixes and uncomment of BeSLighthouse
=> Fixes in Genesis file and env script

beslab/0.0.1/besman-gitlab.sh, beslab_genesis.yaml
Code to get the initial repository / project/ datastore created in Gitlab at installation.
=> GItlab repository/datastore creation programmatically 

beslab/0.0.1/besman-gitlab.sh, beslab_genesis.yaml
=> Updated gitlab installation

beslab/0.0.1/besman-gitlab.sh
Updates in gitlab repo creation and fixes.
=> Updates in gitlab code and fixes

beslab_genesis.yaml
Clear genesis file and added variable for BESMAN
=> Updated genesis file

beslab_genesis.yaml
=> updated lab parameter in genesis file

beslab/0.0.1/besman-gitlab.sh
=> created user and token for beslighthouse

beslab/0.0.1/besman-beslighthouse.sh
=> updated beslighthouse to store instalation path

beslab/0.0.1/besman-beslab-env.sh, beslab/0.0.1/besman-beslighthouse.sh, beslab_genesis.yaml
updated code for version and path passing
=> updated beslight code to use version provided and path for installation

beslab/0.0.1/besman-beslighthouse.sh
use service for beslighthouse if available
=> added beslighthouse service handling code

beslab/0.0.1/besman-beslighthouse.sh, beslab_genesis.yaml
=> beslighthouse to install proxy for CORS issue

beslab/0.0.1/besman-beslighthouse.sh
=> removed extra slash

beslab/0.0.1/besman-beslighthouse.sh, beslab/0.0.1/besman-gitlab.sh, beslab/0.0.1/besman-metadata.json, beslab/0.0.1/besman-opentofu.json, beslab/0.0.1/besman-radius.json, beslab/0.0.1/besman-vulner.json
=> added code for file creation and config fixes

src/besman-beslab-env.sh, src/besman-beslighthouse.sh, src/besman-gitlab.sh, src/besman-log.sh
=> added logging mechanism

src/besman-beslighthouse.sh
create soft links for npm and node binaries so that service can access.
=> create soft links for npm and node binaries

notebooks/BeSLab-Private.ipynb
Private lab playbook documentation update
=> Private lab playbook documentation update

notebooks/BeSLab-Private.ipynb
Playbook documentation typo correction
=> Playbook documentation typo correction

README.md
=> Getting started guide updated

genesis.yaml, src/besman-beslighthouse.sh, src/besman-gitlab.sh
=> Fixes and port changes

docs/_data/navigation.yml, genesis.yaml, src/besman-beslighthouse.sh, src/besman-gitlab.sh
=> Merge to main

src/besman-beslighthouse.sh, src/besman-gitlab.sh
=> updated port for beslightouse and gitlab

ADDING-TO-GENESIS.md, CONTRIBUTING.md, docs/templates/beslab_new_module.sh, src/besman-fossology.sh, src/besman-github.sh, src/besman-jfrog-artifactory.sh, src/besman-sonarqube.sh
updated how to add new tool for BeSLab
=> Updated documentation to add new tool

src/besman-beslighthouse.sh, src/besman-fossology.sh, src/besman-gitlab.sh, src/besman-jfrog-artifactory.sh, src/besman-sonarqube.sh
=> Merge develop to master

genesis.yaml, src/besman-gitlab.sh
=> updated besLab code to import github repos

genesis.yaml, src/besman-gitlab.sh
=> merged develop

src/besman-gitlab.sh
=> fixed besman-gitlab.sh

src/besman-gitlab.sh
=> fixed issues for Gitlab
